-- MySQL Script generated by MySQL Workbench
-- jue 09 nov 2023 03:43:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_domination
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_domination
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_domination` ;
USE `gestion_domination` ;

-- -----------------------------------------------------
-- Table `gestion_domination`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_domination`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(20) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email_usuario` ASC) VISIBLE,
  INDEX `_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `gestion_domination`.`rol` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_domination`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`domicilio` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `altura` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `cpostal` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_domicilio`),
  UNIQUE INDEX `id_UNIQUE` (`id_domicilio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_domination`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `nombre_sede` VARCHAR(45) NOT NULL,
  `domicilio_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_sede`),
  CONSTRAINT `domicilio_id`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `gestion_domination`.`domicilio` (`id_domicilio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestion_domination`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_domination`.`objetoReservable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`objetoReservable` (
  `id_objeto` INT NOT NULL AUTO_INCREMENT,
  `nombre_objeto` VARCHAR(45) NOT NULL,
  `precio_hora` DOUBLE NOT NULL,
  `precio_min` DOUBLE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `sede_id` INT NOT NULL,
  PRIMARY KEY (`id_objeto`),
  INDEX `id_sede_idx` (`sede_id` ASC) VISIBLE,
  CONSTRAINT `sede_id`
    FOREIGN KEY (`sede_id`)
    REFERENCES `gestion_domination`.`sede` (`id_sede`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_domination`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_domination`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `objeto_id` INT NOT NULL,
  `fecha_hora` TIMESTAMP(2) NOT NULL,
  `duracion_hs` INT UNSIGNED NOT NULL,
  `precio_reserva` DOUBLE NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_reservable_idx` (`objeto_id` ASC) VISIBLE,
  CONSTRAINT `id_objeto`
    FOREIGN KEY (`objeto_id`)
    REFERENCES `gestion_domination`.`objetoReservable` (`id_objeto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestion_domination`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
